alert("Hello world! en una ventana");
alert(3);
// document.write("Hello world! escrito literal en el body");
document.write(3);
console.log("Hello world! en la consola");
console.log(3);
console.log('en', 'un', 'lugar', 'de', 'la', 'Mancha');
console.info('Info');
console.warn('Warning dfsjkf dsjkfskjd f');
console.error('Error jfdksjfbsdkjfsbdk');